In [ ]:
import numpy as np

### The Basics

In [ ]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.ndim

1

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.itemsize # 바이트 사이즈

4

In [ ]:
a.nbytes # total byte size

12

In [ ]:
a.size # number of elements

3

### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,5] # specific element [r, c]

13

In [ ]:
a[0, :] # specific row

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,2] #specific column

array([ 3, 10])

In [ ]:
a[0,1:-1:2] #[startindex:endindex:stepsize]

array([2, 4, 6])

In [ ]:
a[1,5]=20

a[:,2]=[1,2]

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[0,1,1]

4

In [ ]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of arrays

In [ ]:
np.zeros((2,3)) # all 0 matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2),dtype='int32') # all 1 matrix

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2),99) # any other number; here 99

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a,4) # any other number

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(4,2) # random decimal number

array([[0.56766701, 0.78349889],
       [0.02693246, 0.73361311],
       [0.77366285, 0.24002523],
       [0.75948857, 0.47251263]])

In [ ]:
np.random.randint(-4,8,size=(3,3)) #random integer value; (start, end, size)

array([[ 7,  5, -3],
       [-2, -1,  5],
       [ 3,  6, -1]])

In [ ]:
np.identity(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0) # repeat array
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.cos(a) # cos func

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [ ]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b) # matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c=np.identity(3) 
np.linalg.det(c) # find determinant

1.0

Statistics

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats) # find minimum value

1

In [ ]:
np.max(stats, axis=1) # find maximum value

array([3, 6])

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # vertically stacking vectors

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack([h1,h2]) # horizontal stack

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [71]:
# 텍스트 파일 -> numpy array로 변경, delimiter: 숫자를 나눌 구분자
filedata=np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/data.txt',delimiter=',') 
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [72]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])